name: BelvensClasses
main: belven.classes.ClassManager
version: 1

commands:
   bchealer:
      description: This will change your class to a healer
      usage: /bchealer 
      permission: BelvensClasses.bchealer
      permission-message: You don't have bchealer
   listclasses:
      description: Lists all players and thier classes
      usage: /listclasses
      permission: BelvensClasses.listclasses
      permission-message: You don't have listclasses
   listabilities:
      description: Lists your classes abilities
      usage: /listabilities
      permission: BelvensClasses.listabilities
      permission-message: You don't have listabilities
   bcmage:
      description: This will change your class to a mage
      usage: /bcmage 
      permission: BelvensClasses.bcmage 
      permission-message: You don't have bcmage 
   bcwarrior:
      description: This will change your class to a warrior
      usage: /bcwarrior 
      permission: BelvensClasses.bcwarrior 
      permission-message: You don't have bcwarrior
   bcassassin:
      description: This will change your class to a assassin
      usage: /bcassassin 
      permission: BelvensClasses.bcassassin 
      permission-message: You don't have assassin
   bcarcher:
      description: This will change your class to a archer
      usage: /bcarcher 
      permission: BelvensClasses.bcarcher 
      permission-message: You don't have archer   
   bcdummy:
      description: Spawns a dummy player entity
      usage: /bcdummy 
      permission: BelvensClasses.bcdummy
      permission-message: You don't have bcdummy