name: BelvensClasses
main: belven.classes.ClassManager
version: 1
depend: [BelvensArenas, BelvensTeams]

commands:
   bchealer:
      description: This will change your class to a healer
      usage: /bchealer 
      permission: BelvensClasses.bchealer
      permission-message: You don't have BelvensClasses.bchealer
   listclasses:
      description: Lists all players and thier classes
      usage: /listclasses
      permission: BelvensClasses.listclasses
      permission-message: You don't have BelvensClasses.listclasses
   listabilities:
      description: Lists your classes abilities
      usage: /listabilities
      permission: BelvensClasses.listabilities
      permission-message: You don't have BelvensClasses.listabilities
   setlevel:
      description: sets the players level
      usage: /setlevel
      permission: BelvensClasses.setlevel
      permission-message: You don't have BelvensClasses.setlevel
   bcmage:
      description: This will change your class to a mage
      usage: /bcmage 
      permission: BelvensClasses.bcmage 
      permission-message: You don't have BelvensClasses.bcmage
   bcmonk:
      description: This will change your class to a monk
      usage: /bcmonk 
      permission: BelvensClasses.bcmonk 
      permission-message: You don't have BelvensClasses.bcmonk
   bcpriest:
      description: This will change your class to a Priest
      usage: /bcpriest 
      permission: BelvensClasses.bcpriest 
      permission-message: You don't have BelvensClasses.bcpriest
   bcwarrior:
      description: This will change your class to a warrior
      usage: /bcwarrior 
      permission: BelvensClasses.bcwarrior 
      permission-message: You don't have BelvensClasses.bcwarrior 
   bcberserker:
      description: This will change your class to a berserker 
      usage: /bcberserker 
      permission: BelvensClasses.bcberserker 
      permission-message: You don't have BelvensClasses.bcberserker 
   bcdaemon:
      description: This will change your class to a daemon 
      usage: /bcdaemon 
      permission: BelvensClasses.bcdaemon 
      permission-message: You don't have BelvensClasses.bcdaemon 
   bcassassin:
      description: This will change your class to a assassin
      usage: /bcassassin 
      permission: BelvensClasses.bcassassin 
      permission-message: You don't have BelvensClasses.bcassassin 
   bcarcher:
      description: This will change your class to a archer
      usage: /bcarcher 
      permission: BelvensClasses.bcarcher 
      permission-message: You don't have BelvensClasses.bcarcher
   bcdummy:
      description: Spawns a dummy player entity
      usage: /bcdummy 
      permission: BelvensClasses.bcdummy
      permission-message: You don't have BelvensClasses.bcdummy
permissions:
    BelvensClasses.*:
        description: Gives access to all of BelvensClasses commands
        children:
            BelvensClasses.BaseClasses.*: true
            BelvensClasses.TierClasses.*: true
    BelvensClasses.BaseClasses.*:
        description: Gives access to all of base classes
        children:
            BelvensClasses.bchealer: true
            BelvensClasses.bcmage: true
            BelvensClasses.bcwarrior: true
            BelvensClasses.bcassassin: true
            BelvensClasses.bcarcher: true
            BelvensClasses.bcberserker: true
            BelvensClasses.listclasses: true
            BelvensClasses.listabilities: true
    BelvensClasses.TierClasses.*:
        description: Gives access to all of tier classes
        children:
            BelvensClasses.bcdaemon: true
            BelvensClasses.bcpriest: true
            BelvensClasses.bcmonk: true
    BelvensClasses.listclasses:
        description: Lists all players and thier classes
        default: op
    BelvensClasses.listabilities:
        description: Lists your classes abilities
        default: op
    BelvensClasses.bcberserker:
        description: This will change your class to a Berserker
        default: true
    BelvensClasses.bcdaemon:
        description: This will change your class to a Daemon
        default: true
    BelvensClasses.bcmage:
        description: This will change your class to a Mage
        default: true
    BelvensClasses.bcmonk:
        description: This will change your class to a Monk
        default: true
    BelvensClasses.bchealer:
        description: This will change your class to a Healer
        default: true
    BelvensClasses.bcpriest:
        description: This will change your class to a Priest
        default: true
    BelvensClasses.bcwarrior:
        description: This will change your class to a Warrior
        default: true
    BelvensClasses.bcassassin:
        description: This will change your class to a Assassin
        default: true
    BelvensClasses.bcarcher:
        description: This will change your class to a Archer
        default: true